### ISSUE TITLE
Ensure terminology is consistent with simulation studies

### ISSUE THREAD

**Issue by statisfactions** [statisfactions/simpr#13]
In the package documentation and variable names, there are lots of terms like *metaparameters* and *replications* that are simply made up.  We should check with someone familiar with the academic simulation literature to ensure this terminology is reasonable.

**Comment by knickodem** [comment]
Feinberg & Rubright (2016) has a section titled "Uses of, and Common Terms in, Simulation" that can be used as a reference.
[Feinberg and Rubright, 2016 - Conducting simulation studies in psychometrics.pdf](https://github.com/statisfactions/simpr/files/4330935/Feinberg.and.Rubright.2016.-.Conducting.simulation.studies.in.psychometrics.pdf)

**Comment by statisfactions** [comment]
Not planning on changing names of verbs for now.
